import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import Head from 'next/head';

export const metadata = {
    title: "Headless WordPress Example",
    description: "Generated by Franly the Manly",
};

export default function RootLayout({children}) {

    return (

        <html>
        <Head>
            <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        </Head>
        <body>

            <main>

                <header className="sticky top-0 z-50 bg-white h-14 shadow flex justify-center" >
                <Navbar/>
                </header>

                {children}


                <footer>
                    <Footer/>
                </footer>
            </main>

        </body>
        </html>
    );
};
