import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

export const metadata = {
    title: "Headless WordPress Example",
    description: "Generated by Franly the Manly",
};

export default function RootLayout({children}) {

    return (

        <html>
        <body>

            <main>

                <header>
                <Navbar/>
            </header>

                {children}


                <footer>
                    <Footer/>
                </footer>
            </main>

        </body>
        </html>
    );
};
