name: Deploy to Front

on:
  push:
    branches:
      - production  # Déclenche le workflow sur chaque push vers production
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "vferrand-smid"
          git config --global user.email "vferrand@smartphone-id.com"

      - name: Authenticate to GitHub
        env:
          WEBSITE_B2C: ${{ secrets.Website_b2c }}
        run: |
          git remote add website_b2c https://x-access-token:${WEBSITE_B2C}@github.com/smartphone-id/website_b2c.git

      - name: Copy content to front folder
        run: |
          mkdir -p temp-website_b2c/front
          rsync -av --exclude=".git" . temp-website_b2c/front

      - name: Commit and push changes
        run: |
          cd temp-website_b2c
          git add front
          git commit -m "Automated update of front content"
          git push website_b2c development

      - name: Debug - Show current directory
        run: pwd

      - name: Debug - List files
        run: ls -la
